### ISSUE TITLE
Can't add new entities

### ISSUE THREAD

**Issue by abubakarsohail** [golastmile/rasa-nlu-trainer#10]
I think the trainer is broken. Can't seem to add new entities.

**Comment by pateelaman1** [comment]
I'm having the same issue. Even in the demo data file provided by default.

**Comment by atiquenazar** [comment]
I m facing this issue  as well, and issue with data format as well. 
it says something about commo_examples not found

**Comment by amn41** [comment]
Ah - looks like I messed something up. Use this one for now : azazdeaz.github.io/rasa-nlu-trainer/

**Comment by abubakarsohail** [comment]
@amn41 that too doesn't seem to be working.

**Comment by atiquenazar** [comment]
@amn41 its not working

**Comment by atiquenazar** [comment]
@amn41 can you please help me with the correct format of training data.

**Comment by azazdeaz** [comment]
It should be working with any JSON file.
Unfortunately, i can't reproduce the issue. Can you add some more details? (ie. browser version, console errors, or steps to reproduce could help)

**Comment by abubakarsohail** [comment]
The trainer seems to be working now. Is there any way the trainer can add examples in common_examples to intent_examples automatically?

**Comment by amn41** [comment]
common examples are automatically used to train the intents, so you don't have to duplicate them there. see http://rasa-nlu.readthedocs.io/en/latest/dataformat.html

**Comment by abubakarsohail** [comment]
But I am getting an error while training data without intent_examples

**Comment by amn41** [comment]
That sounds like a bug. Could you please create an issue on the rasa_nlu repo with exact steps to reproduce?

**Comment by abubakarsohail** [comment]
The link you shared, it says
"In the rasa NLU data format, there are three lists of examples: common_examples, intent_examples, and entity_examples. The common_examples are used to train both the entity and the intent models. In many cases it’s fine to put all of your training examples in there. However, if you need lots and lots of examples to train a good entity recogniser, that can mess up your intent model because your classes are totally unbalanced. In that case it makes sense to split up these lists."
So, am I supposed to split up intent and entity examples?

**Comment by abubakarsohail** [comment]
This is what I get while training my data. It has fewer examples than the demo-rasa.json. demo-rasa.json trains without fail because I think it has separate intent examples. If you think this is something rasa_nlu related, I'll open an issue the repo.
![capture](https://cloud.githubusercontent.com/assets/20099503/23299790/c2813856-faa4-11e6-8619-068842fc0af6.PNG)
![1](https://cloud.githubusercontent.com/assets/20099503/23299793/c4e06eb4-faa4-11e6-883c-2c2fe48d6857.PNG)
![2](https://cloud.githubusercontent.com/assets/20099503/23299800/c912c7e8-faa4-11e6-87a9-64aca058b5d0.PNG)

**Comment by PHLF** [comment]
To get back to the original issue, here is what happens for me using Chrome (I tested with a local install too, with no luck) :

![image](https://cloud.githubusercontent.com/assets/10827301/23548821/951420ee-0009-11e7-8741-a8b785508480.png)

I am not able to add new entities using rasa-nlu-trainer.

**Comment by kamalpy** [comment]
#13 This is a small hack I did to get it working.

**Comment by azazdeaz** [comment]
Thanks @kamalpy! I've deployed it to the online version.

**Comment by kamalpy** [comment]
@azazdeaz Thanks for that.
