### ISSUE TITLE
Unable to Open Examples in Existing Json File demo-rasa.json installed and newly added examples not saving

### ISSUE THREAD

**Issue by avinash-k** [golastmile/rasa-nlu-trainer#16]

**Comment by amn41** [comment]
Thanks for creating this issue. Could you please specify what's not working? Please use the following format:

1. environment (OS, git hash of trainer)
2. steps to reproduce
3. expected behaviour
4. observed behaviour

thanks!

**Comment by naveen-tex** [comment]
Sorry to hijack this issue. Even I was facing the same issue (on macOS 10.12). I think what he was referring to was that the default training data ([from the demo-rasa.json](https://github.com/golastmile/rasa_nlu/blob/master/data/examples/rasa/demo-rasa.json)) has entity_examples & intent_examples objects in the json whereas the rasa-nlu-trainer requires common_examples with the training data json to visualise correctly or you end up with an error (attached). The workaround I tried was to rename the entity_examples to common_examples in the training data set. Hope this helps. Thanks.
<img width="1173" alt="rasa-nlu-trainer error" src="https://cloud.githubusercontent.com/assets/13283217/24174026/9c817bae-0e5c-11e7-9eae-bd86e348edf0.png">

**Comment by amn41** [comment]
thanks for the clarification! have updated that file :) see PR in rasa_nlu repo

**Comment by azazdeaz** [comment]
thanks @naveen-tex , this should have been fixed since v0.2.4.
don't you getting an update notification like this?:
<img width="367" alt="screen shot 2017-03-22 at 20 57 06" src="https://cloud.githubusercontent.com/assets/2298371/24218062/2c0ab1b0-0f42-11e7-8af7-8259294cb755.png">

**Comment by naveen-tex** [comment]
after the updates (to the trainer & the rasa_nlu) everything works. Thanks @amn41 & @azazdeaz

**Comment by azazdeaz** [comment]
Great! :) (I hope that update message works everywhere, it's really hard to test if it pops up when it needed :) )
