### ISSUE TITLE
Unable to use the Save feature in the trainer with larger datasets (> 400 labeled examples)

### ISSUE THREAD

**Issue by naveen-tex** [golastmile/rasa-nlu-trainer#17]
Hi,

I have been playing around with rasa_nlu for quite sometime now (on macOS Sierra 10.12) and it is a great open source replacement for LUIS. And rasa-nlu-trainer is a great visualizer to add/delete examples to the training data set. But what I found was that with larger datasets (greater than 400 labeled examples across 3 intents and 10 entities), the Save functionality was not working and it was throwing up a **413 Payload Too Large error**. I attached the output from the terminal below. I was trying to see if I could increase the limit in the server.js by changing it to "_app.use(bodyParser.json({limit: "50mb"}))_" but that didn't work. Can you please help by suggesting any workarounds or fixes. Thanks.
<img width="812" alt="save functionality error" src="https://cloud.githubusercontent.com/assets/13283217/24174548/18582028-0e5f-11e7-9b41-42568a63f3db.png">

**Comment by azazdeaz** [comment]
Thanks a lot for this issue @naveen-tex!
It is fixed with the npm version 0.2.6 :)

**Comment by naveen-tex** [comment]
Thanks @azazdeaz . Works perfectly now.
