### ISSUE TITLE
Two spaces creating issues & wrong marking

### ISSUE THREAD

**Issue by chatShopper** [golastmile/rasa-nlu-trainer#19]
If there are two spaces in a sentence we get an error when handling the files in the rasa NLU & the following entities are marked wrong (see screenshots). 
<img width="1269" alt="bildschirmfoto 2017-04-18 um 08 53 53" src="https://cloud.githubusercontent.com/assets/18370222/25128738/1e9913d8-243b-11e7-8507-bc6d0aca8dd1.png">

**Comment by azazdeaz** [comment]
Thanks for the issue @chatShopper! Fixed with v0.2.7
