### ISSUE TITLE
update theme in line with rasa.ai webpage

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa-nlu-trainer#3]
Would like to edit the styles. From what I can tell from the [ant-ui docs](https://ant.design/docs/react/use-with-create-react-app), this requires us to `react-scripts eject` & customise the webpack config. Is that right @azazdeaz ? Can we edit the theme while keeping the CRA config?

**Comment by azazdeaz** [comment]
Yes, we have to eject for that :( 
I'll prepare the things for the style customisation 👍

**Comment by amn41** [comment]
Awesome - I tried it out and was able to change the font size :) 
@eliseboyd could you please pull the latest version and see if it works for you? Instructions [here](https://github.com/golastmile/rasa-nlu-trainer/pull/4)

@azazdeaz only issue I have is that when jest is auto-triggered by `git commit`, it doesn't respond to any of the `a, q, Enter` commands.
