### ISSUE TITLE
cancel button in 'new example' modal does not work

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa-nlu-trainer#6]
![image](https://cloud.githubusercontent.com/assets/5114084/22788509/4bc4b348-eee0-11e6-8f02-26ce1baea6b0.png)

steps to reproduce:

1. click 'create new example'
2. click 'cancel'

expected behaviour: modal quits
observed behaviour: no change

**Comment by azazdeaz** [comment]
It was working for me but it's possible that it was buggy with certain antd versions.
I added a possible fix https://github.com/golastmile/rasa-nlu-trainer/commit/4ece3c18f5bb1ac7bc7734d30b4e2778491160ed
Can check if it is working for you too? (i updated the demo here https://golastmile.github.io/rasa-nlu-trainer/ :) )

**Comment by amn41** [comment]
yep works now! thanks :)
