### ISSUE TITLE
Deleting intent deletes the whole sample tab

### ISSUE THREAD

**Issue by AmitPoonia** [golastmile/rasa-nlu-trainer#7]
Step1: Open online version of rasa-nlu-trainer and open the list of intents and you will get something like following screen:
<img width="1026" alt="1" src="https://cloud.githubusercontent.com/assets/10506352/22830695/c7a45f32-efa7-11e6-9460-1816d454c084.png">

Step2: Select two of the intents("restaurant search" and "affirm") and  click on "OK":
<img width="1024" alt="2" src="https://cloud.githubusercontent.com/assets/10506352/22830699/c7aba602-efa7-11e6-8a63-607594017292.png">

Step3: You will get a screen like this:
<img width="1023" alt="3" src="https://cloud.githubusercontent.com/assets/10506352/22830697/c7a72af0-efa7-11e6-8946-d11f65de4bed.png">

Step4: Select the "intent" text of first sample, like in this screen, and try to delete it using delete or backspace button:
<img width="1021" alt="4" src="https://cloud.githubusercontent.com/assets/10506352/22830698/c7a76c18-efa7-11e6-885f-ab75ac86bf91.png">

Step5: And you will end-up with following screen, with one example less:
<img width="1025" alt="5" src="https://cloud.githubusercontent.com/assets/10506352/22830696/c7a65ef4-efa7-11e6-9ded-924ac67d42e6.png">

**Comment by azazdeaz** [comment]
Hi, thanks for the issue! 
I've added the fix. You can test it here: https://golastmile.github.io/rasa-nlu-trainer/
