### ISSUE TITLE
Selected text does not highlight while generating rasa_nlu trainer data online ?

### ISSUE THREAD

**Issue by Shravan40** [golastmile/rasa-nlu-trainer#8]
I am trying to to generate the trianer data using [generate rasa_nlu trainer data online](https://golastmile.github.io/rasa-nlu-trainer/).

While adding the new example, When i enter the text and highlight certain part of it with existing or new intent. It doesn't get save that way. ( I thought i might be saving but i am not able to view it). Hence i tried to train the model and after that made couple of api calls.

Each API calls has produced empty `"entities": [] `

**Comment by azazdeaz** [comment]
Hi @Shravan40 !
I can't reproduce the issue. Could you help me with some more details? (ie. a short gif would be perfect)

**Comment by Shravan40** [comment]
Hey @azazdeaz I have found that selection problem is in Firefox. When i switched to google chrome selected text were highlighted before adding. As soon as i click add button selected text disappear in both the browsers.  Please find the pictures in order. 
![firefox_1](https://cloud.githubusercontent.com/assets/1205111/22927090/7ddcb8be-f2d5-11e6-9dde-bf5b6054ec67.png)
![firefox_2](https://cloud.githubusercontent.com/assets/1205111/22927091/7feef478-f2d5-11e6-85a6-9f1fe9002125.png)
![chrome_1](https://cloud.githubusercontent.com/assets/1205111/22927102/91b5c394-f2d5-11e6-954e-46f2d311e76d.png)
![chrome_2](https://cloud.githubusercontent.com/assets/1205111/22927104/94c008f6-f2d5-11e6-968e-29fe251a86bd.png)

When i download the `testData.json` the file has no entries for `entities`. 
```
{
        "text": "Your debit card 5326XXXXXXXX9414 has been used to make a purchase of INR 866 on 17-OCT-16 at Shri Siddhanth Pharma  Ba.",
        "intent": "merchantsName",
        "entities": []
      },
      {
        "text": "50.00 txn at M/s SHAJAN THERUVA is approved on 24/12/16 with card ending 9414,RR#000510428920,Auth#269336. You agree to pay as per cardholder agreement. chargeslip -",
        "intent": "spendAmount",
        "entities": []
      }
```

Please let me know, If I am doing something wrong.

**Comment by Shravan40** [comment]
I have found the solution

- Click on Add new example
- Enter text into text and intent
- After that click on `+` icon and select text and create entities or select from existing one.

But it's not working in Firefox browser.

**Comment by azazdeaz** [comment]
Hi, thanks for investigating! :)
Unfortunately, Firefox doesn't support selection events yet. I'll add an alert in ff about this.
In other browsers you should be able to add entities in the same way from the "add example" dialog.

**Comment by akshithaadepu** [comment]
Can you please share your code?

**Comment by akshithaadepu** [comment]
Can you please share your code?
