### ISSUE TITLE
demo version not updating

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa-nlu-trainer#9]
Hey @azazdeaz  - might need your help again. I tried to build & publish the latest version. The gh-pages branch has been updated but for some reason the old styling still remains. Could you please try publishing?

**Comment by azazdeaz** [comment]
Hi, i can see the new styling, looks great! :) It could be just the browser cache.

**Comment by azazdeaz** [comment]
ah, i see the issue now

**Comment by azazdeaz** [comment]
closed with https://github.com/golastmile/rasa-nlu-trainer/commit/771ab27900deb4d00df8321edf75f02591136b89
